# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# This provider.tf is auto-generated by Terragrunt
# It configures the Azure provider and sets up the backend
provider "azurerm" {
  features {}
  subscription_id = "856880af-e2ac-41b2-b5fb-e7ebfe4d97bc"
}
terraform {
  backend "azurerm" {}
}
