# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
allowed_ips   = ["163.116.174.113"]
container_cpu = "0.25"
container_env_vars = {
  frontend = [{
    name  = "DB_HOST"
    value = "localhost"
    }, {
    name  = "DB_PORT"
    value = "5432"
  }]
}
container_external_enable      = true
container_image                = "ghcr.io/houssemdellai/containerapps-album-frontend:v1"
container_latest_revision      = true
container_memory               = "0.5Gi"
container_name                 = "frontend"
container_precentage           = 100
container_scale_rule_name      = "http-scaling"
container_target_port          = 3000
container_transport            = "http"
containerapp_volume_name       = "myvolume"
host_environment_short         = "d"
http_concurrent_requests       = 10
http_scale_rule_max_replicas   = 1
http_scale_rule_min_replicas   = 0
region_short                   = "we"
resource_number                = 1
sysrole                        = "frontend"
workload_profile_maximum_count = 1
workload_profile_minimum_count = 0
workload_profile_name          = "Consumption"
workload_profile_type          = "Consumption"
