# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
host_environment_short = "p"
region                 = "West Europe"
region_short           = "we"
sysrole                = "containerapps"
