remote_state {
  backend = "azurerm"
  config = {
    subscription_id      = "SUB_ID"
    resource_group_name  = "eraki_terragruntdemo_rg_1001"
    storage_account_name = "erakitfstateaccount17107"
    container_name       = "terragruntstatecontainer"
    key                  = "${path_relative_to_include()}/advancedContainerApps/terragrunt.tfstate"
  }
}

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite"
  contents  = <<EOF
# This provider.tf is auto-generated by Terragrunt
# It configures the Azure provider and sets up the backend
provider "azurerm" {
  features {}
  subscription_id = "SUB_ID"
}
terraform {
  backend "azurerm" {}
}
EOF
}
