# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
host_environment_short = "p"
region                 = "West Europe"
region_short           = "we"
resource_group_name    = "RG-p-we-containerapps"
resource_number        = "01"
retention_in_days      = 30
sysrole                = "sharedapps"
