# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
host_environment_short = "d"
region                 = "westeurope"
region_short           = "we"
sysrole                = "containerapps"
