# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
address_space          = ["10.0.0.0/16"]
host_environment_short = "d"
region                 = "westeurope"
region_short           = "we"
resource_number        = "01"
subnet_prefixes        = ["10.0.1.0/24"]
sysrole                = "containerapps"
