remote_state {
  backend = "azurerm"
  config = {
    subscription_id      = "856880af-e2ac-41b2-b5fb-e7ebfe4d97bc"
    resource_group_name  = "eraki_terragruntdemo_rg_1001"
    storage_account_name = "erakitfstateaccount17107"
    container_name       = "advterragruntcontainer03"
    key                  = "Dev/${path_relative_to_include()}/terragrunt.tfstate"
  }
}

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite"
  contents  = <<EOF
# This provider.tf is auto-generated by Terragrunt
# It configures the Azure provider and sets up the backend
provider "azurerm" {
  features {}

  # Retry configuration to handle throttling and transient errors
  # retry {
  #   max_retries = 5
  #   retry_delay = 10
  # }
  resource_provider_registrations = "none"
  subscription_id = "856880af-e2ac-41b2-b5fb-e7ebfe4d97bc"
}
terraform {
  backend "azurerm" {}
}
EOF
}

