# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# This provider.tf is auto-generated by Terragrunt
# It configures the Azure provider and sets up the backend
provider "azurerm" {
  features {}

  # Retry configuration to handle throttling and transient errors
  # retry {
  #   max_retries = 5
  #   retry_delay = 10
  # }
  resource_provider_registrations = "none"
  subscription_id                 = "SUB_ID"
}
terraform {
  backend "azurerm" {}
}
