# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
host_environment_short         = "d"
region_short                   = "we"
resource_number                = 1
sysrole                        = "containerapps"
workload_profile_maximum_count = 1
workload_profile_minimum_count = 0
workload_profile_name          = "Consumption"
workload_profile_type          = "Consumption"
